

// const standardSyntaxes = [
//   '@incollection{in_collection,
//       author       = {Peter Farindon},
//       title        = {The title of the work},
//       booktitle    = {The title of the book},
//       publisher    = {The name of {the" publisher},
//       year         = 1993,
//       editor       = {The editor},
//       volume       = 4,
//       series       = 5,
//       chapter      = 8,
//       pages        = {201-213,
//       address      = {The address of the publisher",
//       edition      = 3,
//       month        = 7,
//       note         = "An optional note"
//     }',
//     '@incollection"in_collection,
//       author       = "Peter Farindon",
//       title        = "The title of the work",
//       booktitle    = "The title of the book",
//       publisher    = "The name of the publisher",
//       year         = 1993,
//       editor       = "The editor",
//       volume       = 4,
//       series       = 5,
//       chapter      = 8,
//       pages        = "201-213",
//       address      = "The address of the publisher",
//       edition      = 3,
//       month        = 7,
//       note         = "An optional note"
//     }',
//     '@incollection"in_collection,
//       author       = "Peter Farindon",
//       title        = "The title of {the} work",
//       booktitle    = "The title of the book",
//       publisher    = "The {name {of} the} publisher",
//       year         = 1993,
//       editor       = "The editor",
//       volume       = 4,
//       series       = 5,
//       chapter      = 8,
//       pages        = "201-213",
//       address      = "The address of the publisher",
//       edition      = 3,
//       month        = 7,
//       note         = "An optional note"
//     }'
// ]

const standardOutput = {
  citeKey : 'in_collection',
  bibType : 'incollection',
  author : 'Peter Farindon',
  title : 'The title of the work',
  booktitle : 'The title of the book',
  publisher : 'The name of the publisher',
  year : '1993',
  editor : 'The editor',
  volume : '4',
  series : '5',
  chapter : '8',
  pages : '201-213',
  address : 'The address of the publisher',
  edition : '3',
  month : '7',
  note : 'An optional note'
}

// const moduloSyntaxes = [
//   '@incollection{in_collection,
//       author       = {Peter Farindon},
//       author       = {Jimmy Hendrix},
//       keyword     = {test1},
//       keyword     = {test2},
//       title        = {The title of the work},
//       booktitle    = {The title of the book},
//       publisher    = {The name of {the} publisher},
//       year         = 1993,
//       editor       = {The editor",
//       volume       = 4,
//       series       = 5,
//       chapter      = 8,
//       pages        = {201-213",
//       address      = {The address of the publisher},
//       edition      = 3,
//       month        = 7,
//       note         = {An optional note}
//     }',
//     '@incollection"in_collection,
//       author       = "Peter Farindon",
//       author       = "Jimmy Hendrix",
//       keyword      = "test1",
//       keyword      = "test2",
//       title        = "The title of the work",
//       booktitle    = "The title of the book",
//       publisher    = "The name of the publisher",
//       year         = 1993,
//       editor       = "The editor",
//       volume       = 4,
//       series       = 5,
//       chapter      = 8,
//       pages        = "201-213",
//       address      = "The address of the publisher",
//       edition      = 3,
//       month        = 7,
//       note         = "An optional note"
//     }',
//     '@incollection"in_collection,
//       author       = "Peter Farindon",
//       author       = "Jimmy {H}endrix",
//       keyword      = "test1",
//       keyword      = "test2",
//       title        = "The title of {the} work",
//       booktitle    = "The title of the book",
//       publisher    = "The {name {of} the} publisher",
//       year         = 1993,
//       editor       = "The editor",
//       volume       = 4,
//       series       = 5,
//       chapter      = 8,
//       pages        = "201-213",
//       address      = "The address of the publisher",
//       edition      = 3,
//       month        = 7,
//       note         = "An optional note"
//     }'
// ]

const moduloOutput = {
  citeKey : 'in_collection',
  bibType : 'incollection',
  authors : ['Peter Farindon', 'Jimmy Hendrix'],
  keywords : ['test1', 'test2'],
  title : 'The title of the work',
  booktitle : 'The title of the book',
  publisher : 'The name of the publisher',
  year : '1993',
  editor : 'The editor',
  volume : '4',
  series : '5',
  chapter : '8',
  pages : '201-213',
  address : 'The address of the publisher',
  edition : '3',
  month : '7',
  note : 'An optional note'
}
